import {type TimezoneResponse} from './ApiResponse.type';
import {type BankAccountResponse} from './BankAccount.type';
import {type BankAccountDTOResponse} from './BankAccountDTO.type';
import {type BuildingResponse} from './Building.type';
import {type BuildingDTOResponse} from './BuildingDTO.type';
import {type CompanyResponse} from './Company.type';
import {type DonationResponse} from './Donation.type';
import {type HouseResponse} from './House.type';
import {type HouseDTOResponse} from './HouseDTO.type';
import {type LicenseResponse} from './License.type';
import {type PhoneResponse} from './Phone.type';
import {type PhonebookResponse} from './Phonebook.type';
import {type PositionResponse} from './Position.type';
import {type RentalResponse} from './Rental.type';

export type ProfileResponse = {
  id: number;
  pid: string;
  guid: string;
  name: string;
  cash: number;
  bankacc: number;
  coplevel: string;
  mediclevel: string;
  adaclevel: string;
  adminlevel: string;
  donatorlvl: string;
  justizlevel: string;
  arrested: number;
  citizen: number;
  tutorial: number;
  dsgvo: number;
  level: number;
  exp: number;
  skillpoint: number;
  hunger: number;
  thirst: number;
  tuning_tickets: number;
  jail_time: number;
  quest_daily: number;
  quest_row: number;
  pos: PositionResponse;
  pos_alive: number;
  pos_free: number;
  suspended: number;
  second_char: number;
  server_id: number;
  chat_muted: number;
  joined_at: string;
  updated_at: string;
  created_at: string;
  avatar: string;
  avatar_full: string;
  avatar_medium: string;
  profilename: string;
  profileurl: string;
  last_seen: TimezoneResponse;
  level_progress: number;
  donations: DonationResponse[];
  /** Playtime in minutes */
  play_time: {
    active: number;
    total: number;
  };
  garage: {
    value: number;
    count: number;
  };
  houses: HouseResponse[];
  houses_keyed: HouseDTOResponse[];
  rentals: RentalResponse[];
  buildings: BuildingResponse[];
  buildings_keyed: BuildingDTOResponse[];
  phones: PhoneResponse[];
  company_owned: CompanyResponse[];
  phonebooks: PhonebookResponse[];
  licenses: LicenseResponse[];
  bank_main: BankAccountResponse[];
  banks: BankAccountDTOResponse[];
};
