name: Publish Google Play Store Build

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build_aab, publish_playstore]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Create `google-services.json`
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/A3PLI/A3PLI/google-services.json

      - name: Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build app
        id: build
        run: eas build -p android --profile production --local

      - name: 🔼 Upload Artifact if build successful
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: 'Build Artifact'
          path: /home/runner/work/A3PLI/A3PLI/build-*.aab

      - name: 🎉 Submit app
        run: eas submit -p android --profile production --path=/home/runner/work/A3PLI/A3PLI/build-*.aab
